--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 13/02/2021 03:23:25
-- Server version: 5.7.19-log
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE `10384_db_crmall_test`;

--
-- Drop table `client`
--
DROP TABLE IF EXISTS client;

--
-- Drop table `gender`
--
DROP TABLE IF EXISTS gender;

--
-- Set default database
--
USE `10384_db_crmall_test`;

--
-- Create table `gender`
--
CREATE TABLE gender (
  Id INT(11) NOT NULL AUTO_INCREMENT,
  Description VARCHAR(255) NOT NULL,
  IsActive TINYINT(1) NOT NULL,
  CreatAt DATETIME NOT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `client`
--
CREATE TABLE client (
  Id INT(11) NOT NULL AUTO_INCREMENT,
  Name VARCHAR(255) NOT NULL,
  DateBirth DATETIME NOT NULL,
  GenderId INT(11) NOT NULL,
  Cep VARCHAR(9) DEFAULT NULL,
  Address VARCHAR(255) DEFAULT NULL,
  Number VARCHAR(50) DEFAULT NULL,
  Complement VARCHAR(255) DEFAULT NULL,
  Neighborhood VARCHAR(255) DEFAULT NULL,
  State VARCHAR(255) DEFAULT NULL,
  City VARCHAR(255) DEFAULT NULL,
  IsUpdate TINYINT(1) NOT NULL,
  CreatAt DATETIME NOT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6,
AVG_ROW_LENGTH = 3276,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

-- 
-- Dumping data for table gender
--
INSERT INTO gender VALUES
(1, 'Masculino', 1, '2021-02-10 00:00:00'),
(2, 'Feminino', 1, '2021-02-10 00:00:00'),
(3, 'Outros', 1, '2021-02-10 00:00:00');

-- 
-- Dumping data for table client
--
INSERT INTO client VALUES
(1, 'Carlos Alves Soares', '1992-09-05 00:00:00', 1, '87075-706', 'Rua Pioneiro Amadeu Boggio Merlo', '241', '', 'Parque Hortência', 'PR', 'Maringá', 1, '2021-02-13 18:07:15'),
(2, 'Vanessa da conceição', '1996-09-29 00:00:00', 2, '87075-706', 'Rua Pioneiro Amadeu Boggio Merlo', '241', '', 'Parque Hortência', 'PR', 'Maringá', 1, '2021-02-13 18:09:59'),
(3, 'Junior Alves', '1982-05-01 00:00:00', 1, '87075-500', 'Rua Pioneiro José Lopes de Covos', '304', '', 'Conjunto Habitacional João de Barro Thaís', 'PR', 'Maringá', 0, '2021-02-12 22:44:50'),
(4, 'Juliane Torres', '1992-09-05 00:00:00', 2, '', '', '', '', '', '', '', 1, '2021-02-13 18:09:36'),
(5, 'Antonio Maris', '2001-10-25 00:00:00', 1, '87750-000', '', '', '', '', 'PR', 'Alto Paraná', 1, '2021-02-13 18:32:19');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;